### ISSUE TITLE
baking soda, not baking powder

### ISSUE THREAD

**Issue by shigmas** [niw/ramen#4]
Maybe you like the taste of baking powder, but generally, the purpose of baking soda/powder is to add the alkaline, aka 鹹水). Baking powder adds the alkaline, but also neutralizes it. Baking soda just has the alkaline. If you want an even better alkaline, [bake](https://www.nytimes.com/2010/09/15/dining/15curious.html?_r=0) the baking soda.

**Comment by niw** [comment]
Thank you so much, true, it’s not baking powder but baking soda... That’s my mistake for sure!
And true, it’s alternative to 鹹水. Let me fix it.

**Comment by niw** [comment]
Updated! Thank you!!
